// Step in the multi-step flow
export type Step = 'upload' | 'analysis' | 'results' | 'detail';

// Dynamic question generated by LLM
export interface Question {
  id: string;
  question: string;
  options: string[];
}

// SOW Analysis from LLM
export interface SOWAnalysis {
  projectType: string;
  deliverables: string[];
  technicalRequirements: string[];
  integrations: string[];
  questions: Question[];
}

// User's answer to a question
export interface QuestionAnswer {
  questionId: string;
  answer: string;
}

// GitHub repository result
export interface RepoResult {
  id: number;
  owner: string;
  name: string;
  fullName: string;
  description: string | null;
  stars: number;
  language: string | null;
  lastActivity: string;
  coveragePercentage: number;
  covers: string[];
  gaps: string[];
  url: string;
}

// Detailed repository information
export interface RepoDetail {
  // Basic info
  owner: string;
  name: string;
  fullName: string;
  description: string | null;
  url: string;

  // Health metrics
  stars: number;
  forks: number;
  openIssues: number;
  contributors: number;
  lastCommit: string;
  healthStatus: 'active' | 'stale' | 'abandoned';

  // README
  readmeSummary: string;

  // SOW Fit Analysis (LLM-generated)
  fitAnalysis: {
    covers: string[];
    gaps: string[];
    timeSaved: string;
    recommendedModifications: string[];
    risks: string[];
  };
}

// Application state interface
export interface AppState {
  // Current step
  currentStep: Step;
  setCurrentStep: (step: Step) => void;

  // SOW content
  sowContent: string | null;
  filename: string | null;
  setSOWContent: (content: string, filename?: string) => void;

  // Analysis
  analysis: SOWAnalysis | null;
  setAnalysis: (analysis: SOWAnalysis) => void;

  // Question answers
  questionAnswers: Record<string, string>;
  setQuestionAnswer: (questionId: string, answer: string) => void;

  // Additional context
  additionalContext: string;
  setAdditionalContext: (context: string) => void;

  // Search results
  searchResults: RepoResult[];
  setSearchResults: (results: RepoResult[]) => void;

  // Selected repo for detail view
  selectedRepo: RepoDetail | null;
  setSelectedRepo: (repo: RepoDetail | null) => void;

  // Loading states
  isAnalyzing: boolean;
  setIsAnalyzing: (loading: boolean) => void;

  isSearching: boolean;
  setIsSearching: (loading: boolean) => void;

  isLoadingDetail: boolean;
  setIsLoadingDetail: (loading: boolean) => void;

  // Error state
  error: string | null;
  setError: (error: string | null) => void;

  // Reset function
  reset: () => void;
}
